---
title: "AssemblyQc"
author: "Allan Zuza"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Collect spades assembly stats from Quast
```{r load_packages, message=FALSE}
library(tidyverse)
library(janitor)
library(patchwork)
library(viridisLite)

'%notin%' <- Negate('%in%')

```

```{r message=FALSE}
shovil_quast <-
  read_csv(file = "./results/Qc/quast/spades_assemblies/transposed_report.csv") %>%
  filter(Assembly %notin% c("CAA8N9", "CAAUE8")) %>%
  clean_names()

shovil_quast

hybrid_quast <-
  read_csv(file = "./results/Qc/quast/hybrid_assemblies/transposed_report.csv") %>%
  clean_names()

hybrid_quast

quast_output <- 
  rbind(hybrid_quast, shovil_quast)
head(quast_output)

colnames(quast_output)

quast_output[6:nrow(quast_output) ,] %>% select(total_length) %>% summary()

# create violin plots with Assembly stats
y_axis_size = 15
length <-
  shovil_quast %>% select(total_length) %>%
  gather(key="MesureType", value="Val") %>%
  ggplot( aes(x=MesureType, y=Val, fill=MesureType)) +
    geom_violin(
                show.legend = FALSE,
                draw_quantiles = TRUE) + 
    scale_fill_viridis_d() +
    theme_minimal() +
    ylab("Total Assembly Length") +
   xlab("") +
    theme(axis.text.x = element_blank(),
          axis.text.y = element_text(size = 12),
          axis.title.y = element_text(face = "bold", size = y_axis_size))



gc <-
  shovil_quast %>% select(gc_percent) %>%
  gather(key="MesureType", value="Val") %>%
  ggplot( aes(x=MesureType, y=Val, fill=MesureType)) +
    geom_violin(
                show.legend = FALSE,
                draw_quantiles = TRUE) + 
    scale_fill_viridis_d() +
    theme_minimal() +
    ylab("% GC content") +
   xlab("") + theme(axis.text.x = element_blank(),
                    axis.text.y = element_text(size = 12),
                    axis.title.y = element_text(face = "bold", size = y_axis_size))
 
n50 <-
  shovil_quast %>% select(n50) %>%
  gather(key="MesureType", value="Val") %>%
  ggplot( aes(x=MesureType, y=Val, fill=MesureType)) +
    geom_violin(
                show.legend = FALSE,
                draw_quantiles = TRUE) + 
    scale_fill_viridis_d() +
    theme_minimal() +
    ylab("N50") +
   xlab("") + theme(axis.text.x = element_blank(),
                    axis.text.y = element_text(size = 12),
                    axis.title.y = element_text(face = "bold", size = y_axis_size))


contigs <-
  shovil_quast %>% select(number_contigs) %>%
  gather(key="MesureType", value="Val") %>%
  ggplot( aes(x=MesureType, y=Val, fill=MesureType)) +
    geom_violin(
                show.legend = FALSE,
                draw_quantiles = TRUE) + 
    scale_fill_viridis_d() +
  theme_minimal() +
    ylab("Number of Contigs") +
    xlab("") + theme(axis.text.x = element_blank(),
                     axis.text.y = element_text(size = 12),
                     axis.title.y = element_text(face = "bold", size = y_axis_size))


fraction_covered <-
  shovil_quast %>% select(genome_fraction_percent) %>%
  gather(key="MesureType", value="Val") %>%
  ggplot( aes(x=MesureType, y=Val, fill=MesureType)) +
    geom_violin(
                show.legend = FALSE,
                draw_quantiles = TRUE) + 
    scale_fill_viridis_d() +
  theme_minimal() +
    ylab("Reference Genome Covered (%)") +
    xlab("") + theme(axis.text.x = element_blank(),
                     axis.text.y = element_text(size = 12),
                     axis.title.y = element_text(face = "bold", size = y_axis_size))

p <- 
  length + contigs + fraction_covered + n50 +
    plot_annotation(tag_levels = "A",
                    title = "Basic Assembly stats produced by QUAST",
                    theme = theme(plot.title =
                                    element_text(hjust = 0.5,
                                                 face = "bold",
                                                 size = 20)))
p

```

```{r save_the_plots, eval=FALSE}
#save the qc data
plotting_dir <- file.path("results/plots/r", Sys.Date())
plot_name <- file.path(plotting_dir, "illumina_assembly_stats.jpeg")

if (!dir.exists(plotting_dir)) {dir.create(plotting_dir, recursive = TRUE)}

ggsave(filename =  plot_name,
      plot =  p,
      scale = .7,
      width = 14,
      height = 8)

```

